# Generated by Django 5.1.6 on 2025-03-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='responsible_chat',
            field=models.CharField(blank=True, help_text='Укажите numeric chat_id или чата/группы для уведомлений', max_length=100, null=True),
        ),
    ]
