# Generated by Django 5.1.6 on 2025-03-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_responsible_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='responsible_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
