# Generated by Django 5.1.6 on 2025-03-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userquestion_responsible_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='responsible_topic_id',
            field=models.CharField(blank=True, help_text='Укажите ID топика (message_thread_id) в форуме', max_length=50, null=True),
        ),
    ]
