# Generated by Django 5.1.6 on 2025-03-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userquestion_responsible_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='responsible_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
