# Generated by Django 5.1.6 on 2025-03-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userquestion_responsible_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestion',
            name='responsible_name',
        ),
    ]
