# Generated by Django 5.1.6 on 2025-03-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_userquestion_responsible_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='ID пользователя из Telegram', unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('truck_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
