# Generated by Django 5.1.6 on 2025-03-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_company_remove_teleuser_last_name_teleuser_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_chat_id', models.CharField(blank=True, help_text='Укажите ID чата/группы для уведомлений', max_length=100, null=True)),
            ],
        ),
    ]
