# Generated by Django 5.1.6 on 2025-05-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_botconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuser',
            name='accounting_topic_id',
            field=models.CharField(blank=True, help_text='ID топика для Accounting', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teleuser',
            name='operations_topic_id',
            field=models.CharField(blank=True, help_text='ID топика для Operations', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teleuser',
            name='safety_topic_id',
            field=models.CharField(blank=True, help_text='ID топика для Safety', max_length=50, null=True),
        ),
    ]
