# Generated by Django 5.1.6 on 2025-05-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teleuser_accounting_topic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='responsible_chat',
            field=models.IntegerField(blank=True, help_text='Укажите numeric chat_id или чата/группы для уведомлений', null=True),
        ),
    ]
