# Generated by Django 5.1.6 on 2025-05-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_category_responsible_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleuser',
            name='accounting_topic_id',
            field=models.IntegerField(blank=True, help_text='ID топика для Accounting', null=True),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='operations_topic_id',
            field=models.IntegerField(blank=True, help_text='ID топика для Operations', null=True),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='safety_topic_id',
            field=models.IntegerField(blank=True, help_text='ID топика для Safety', null=True),
        ),
    ]
