# Generated by Django 5.1.6 on 2025-05-15 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_teleuser_accounting_topic_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestion',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='company',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='content_photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='content_voice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='mention_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
