# Generated by Django 5.1.6 on 2025-10-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_manager_topic_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managergroup',
            options={'verbose_name': 'Manager group', 'verbose_name_plural': 'Manager groups'},
        ),
        migrations.AlterModelOptions(
            name='managertopic',
            options={'verbose_name': 'Manager topic', 'verbose_name_plural': 'Manager topics'},
        ),
        migrations.RenameIndex(
            model_name='managertopic',
            new_name='main_manage_group_i_2997f9_idx',
            old_name='main_mgrtopic_group_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='managertopic',
            new_name='main_manage_group_i_f0b988_idx',
            old_name='main_mgrtopic_group_topic_idx',
        ),
    ]
